# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Front.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1022, 867)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("logo2424.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QWidget {\n"
"    background-color: #ffffff;\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setStyleSheet("/* =========================\n"
"   QTabWidget – Base\n"
"   ========================= */\n"
"QTabWidget::pane {\n"
"    border: 1px solid #142a5c;\n"
"    background: #f5f8fc;\n"
"    top: -1px;\n"
"}\n"
"\n"
"/* =========================\n"
"   QTabBar – Base Tabs\n"
"   ========================= */\n"
"QTabBar::tab {\n"
"    background: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #2a4da3,\n"
"        stop:1 #1f3c88\n"
"    );\n"
"\n"
"    color: white;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 11px;\n"
"    font-weight: 600;\n"
"\n"
"    padding: 10px 20px;\n"
"    margin-right: 4px;\n"
"\n"
"    border: 0px solid #142a5c;\n"
"    border-bottom: none;\n"
"\n"
"    border-top-left-radius: 8px;\n"
"    border-top-right-radius: 8px;\n"
"\n"
"    min-width: 120px;\n"
"}\n"
"\n"
"/* =========================\n"
"   Hover (Soft Cyan Accent)\n"
"   ========================= */\n"
"QTabBar::tab:hover {\n"
"    background: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #4fc3dc,\n"
"        stop:1 #1f3c88\n"
"    );\n"
"}\n"
"\n"
"/* =========================\n"
"   Selected Tab (Same as Hover)\n"
"   ========================= */\n"
"QTabBar::tab:selected {\n"
"    background: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #4fc3dc,\n"
"        stop:1 #1f3c88\n"
"    );\n"
"\n"
"    color: white;\n"
"    border: 0px solid #142a5c;\n"
"    border-bottom: 2px solid #4fc3dc;\n"
"}\n"
"\n"
"/* Lift selected tab slightly (3D feel) */\n"
"QTabBar::tab:selected {\n"
"    margin-top: -2px;\n"
"}\n"
"\n"
"/* =========================\n"
"   Disabled Tab\n"
"   ========================= */\n"
"QTabBar::tab:disabled {\n"
"    background: #bfcbe6;\n"
"    color: #6b7aa8;\n"
"}\n"
"")
        self.tabWidget.setIconSize(QtCore.QSize(22, 22))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.System_Status_label = QtWidgets.QLabel(self.tab)
        self.System_Status_label.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.System_Status_label.setFont(font)
        self.System_Status_label.setStyleSheet("background-color:lightgreen;")
        self.System_Status_label.setAlignment(QtCore.Qt.AlignCenter)
        self.System_Status_label.setObjectName("System_Status_label")
        self.gridLayout_2.addWidget(self.System_Status_label, 0, 0, 1, 1)
        self.Sensors_groupBox = QtWidgets.QGroupBox(self.tab)
        self.Sensors_groupBox.setMinimumSize(QtCore.QSize(0, 280))
        self.Sensors_groupBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Sensors_groupBox.setFont(font)
        self.Sensors_groupBox.setObjectName("Sensors_groupBox")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.Sensors_groupBox)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.tableWidget = QtWidgets.QTableWidget(self.Sensors_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tableWidget.setFont(font)
        self.tableWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(240)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(True)
        self.tableWidget.verticalHeader().setSortIndicatorShown(True)
        self.tableWidget.verticalHeader().setStretchLastSection(True)
        self.gridLayout_13.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.Sensors_groupBox, 1, 0, 1, 1)
        self.Plots_groupBox = QtWidgets.QGroupBox(self.tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Plots_groupBox.setFont(font)
        self.Plots_groupBox.setObjectName("Plots_groupBox")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.Plots_groupBox)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.Plots_groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.temp_graphicsView = QtWidgets.QGraphicsView(self.groupBox)
        self.temp_graphicsView.setObjectName("temp_graphicsView")
        self.gridLayout_5.addWidget(self.temp_graphicsView, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.Plots_groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.vibration_graphicsView = QtWidgets.QGraphicsView(self.groupBox_2)
        self.vibration_graphicsView.setObjectName("vibration_graphicsView")
        self.gridLayout_6.addWidget(self.vibration_graphicsView, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.Plots_groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.speed_graphicsView = QtWidgets.QGraphicsView(self.groupBox_3)
        self.speed_graphicsView.setObjectName("speed_graphicsView")
        self.gridLayout_7.addWidget(self.speed_graphicsView, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.gridLayout_9.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_6 = QtWidgets.QGroupBox(self.Plots_groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.pressure_graphicsView = QtWidgets.QGraphicsView(self.groupBox_6)
        self.pressure_graphicsView.setObjectName("pressure_graphicsView")
        self.gridLayout_10.addWidget(self.pressure_graphicsView, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.groupBox_6)
        self.groupBox_4 = QtWidgets.QGroupBox(self.Plots_groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.optical_counters_graphicsView = QtWidgets.QGraphicsView(self.groupBox_4)
        self.optical_counters_graphicsView.setObjectName("optical_counters_graphicsView")
        self.gridLayout_8.addWidget(self.optical_counters_graphicsView, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.groupBox_4)
        self.gridLayout_9.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.Plots_groupBox, 2, 0, 1, 1)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Icons/icons8-dashboard-22.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab, icon1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.Alarm_Log_textBrowser = QtWidgets.QTextBrowser(self.tab_2)
        self.Alarm_Log_textBrowser.setObjectName("Alarm_Log_textBrowser")
        self.verticalLayout.addWidget(self.Alarm_Log_textBrowser)
        self.Clear_Alarms_Button = QtWidgets.QPushButton(self.tab_2)
        self.Clear_Alarms_Button.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #2a4da3,\n"
"        stop:1 #1f3c88\n"
"    );\n"
"\n"
"    color: white;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 13px;\n"
"    font-weight: 600;\n"
"\n"
"    padding: 8px 20px;\n"
"    padding-bottom: 10px;\n"
"\n"
"    border-radius: 8px;\n"
"    border: 1px solid #142a5c;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #4fc3dc,\n"
"        stop:1 #1f3c88\n"
"    );\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1f3c88;\n"
"    padding-top: 10px;\n"
"    padding-bottom: 8px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #9fb0d9;\n"
"    color: #eeeeee;\n"
"    border: 1px solid #7a8bb5;\n"
"}\n"
"")
        self.Clear_Alarms_Button.setObjectName("Clear_Alarms_Button")
        self.verticalLayout.addWidget(self.Clear_Alarms_Button)
        self.gridLayout_11.addLayout(self.verticalLayout, 0, 0, 1, 1)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Icons/icons8-alarm-22.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_2, icon2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.Live_Log_Viewer_textBrowser = QtWidgets.QTextBrowser(self.tab_3)
        self.Live_Log_Viewer_textBrowser.setObjectName("Live_Log_Viewer_textBrowser")
        self.verticalLayout_2.addWidget(self.Live_Log_Viewer_textBrowser)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.Restart_Simulation_Button = QtWidgets.QPushButton(self.tab_3)
        self.Restart_Simulation_Button.setMinimumSize(QtCore.QSize(160, 30))
        self.Restart_Simulation_Button.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #2a4da3,\n"
"        stop:1 #1f3c88\n"
"    );\n"
"\n"
"    color: white;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 13px;\n"
"    font-weight: 600;\n"
"\n"
"    padding: 8px 20px;\n"
"    padding-bottom: 10px;\n"
"\n"
"    border-radius: 8px;\n"
"    border: 1px solid #142a5c;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #4fc3dc,\n"
"        stop:1 #1f3c88\n"
"    );\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1f3c88;\n"
"    padding-top: 10px;\n"
"    padding-bottom: 8px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #9fb0d9;\n"
"    color: #eeeeee;\n"
"    border: 1px solid #7a8bb5;\n"
"}\n"
"")
        self.Restart_Simulation_Button.setObjectName("Restart_Simulation_Button")
        self.horizontalLayout_3.addWidget(self.Restart_Simulation_Button)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.Force_Refresh_Button = QtWidgets.QPushButton(self.tab_3)
        self.Force_Refresh_Button.setMinimumSize(QtCore.QSize(160, 30))
        self.Force_Refresh_Button.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #2a4da3,\n"
"        stop:1 #1f3c88\n"
"    );\n"
"\n"
"    color: white;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 13px;\n"
"    font-weight: 600;\n"
"\n"
"    padding: 8px 20px;\n"
"    padding-bottom: 10px;\n"
"\n"
"    border-radius: 8px;\n"
"    border: 1px solid #142a5c;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #4fc3dc,\n"
"        stop:1 #1f3c88\n"
"    );\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1f3c88;\n"
"    padding-top: 10px;\n"
"    padding-bottom: 8px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #9fb0d9;\n"
"    color: #eeeeee;\n"
"    border: 1px solid #7a8bb5;\n"
"}\n"
"")
        self.Force_Refresh_Button.setObjectName("Force_Refresh_Button")
        self.horizontalLayout_3.addWidget(self.Force_Refresh_Button)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.Snapshot_of_Values_Button = QtWidgets.QPushButton(self.tab_3)
        self.Snapshot_of_Values_Button.setMinimumSize(QtCore.QSize(160, 30))
        self.Snapshot_of_Values_Button.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #2a4da3,\n"
"        stop:1 #1f3c88\n"
"    );\n"
"\n"
"    color: white;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 13px;\n"
"    font-weight: 600;\n"
"\n"
"    padding: 8px 20px;\n"
"    padding-bottom: 10px;\n"
"\n"
"    border-radius: 8px;\n"
"    border: 1px solid #142a5c;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #4fc3dc,\n"
"        stop:1 #1f3c88\n"
"    );\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1f3c88;\n"
"    padding-top: 10px;\n"
"    padding-bottom: 8px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #9fb0d9;\n"
"    color: #eeeeee;\n"
"    border: 1px solid #7a8bb5;\n"
"}\n"
"")
        self.Snapshot_of_Values_Button.setObjectName("Snapshot_of_Values_Button")
        self.horizontalLayout_3.addWidget(self.Snapshot_of_Values_Button)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.Clear_Alarms_Maintainance_Button = QtWidgets.QPushButton(self.tab_3)
        self.Clear_Alarms_Maintainance_Button.setMinimumSize(QtCore.QSize(160, 30))
        self.Clear_Alarms_Maintainance_Button.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #2a4da3,\n"
"        stop:1 #1f3c88\n"
"    );\n"
"\n"
"    color: white;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 13px;\n"
"    font-weight: 600;\n"
"\n"
"    padding: 8px 20px;\n"
"    padding-bottom: 10px;\n"
"\n"
"    border-radius: 8px;\n"
"    border: 1px solid #142a5c;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #4fc3dc,\n"
"        stop:1 #1f3c88\n"
"    );\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1f3c88;\n"
"    padding-top: 10px;\n"
"    padding-bottom: 8px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #9fb0d9;\n"
"    color: #eeeeee;\n"
"    border: 1px solid #7a8bb5;\n"
"}\n"
"")
        self.Clear_Alarms_Maintainance_Button.setObjectName("Clear_Alarms_Maintainance_Button")
        self.horizontalLayout_3.addWidget(self.Clear_Alarms_Maintainance_Button)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Icons/icons8-maintenance-22.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_3, icon3, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1022, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Production Line Sensor Dashboard "))
        self.System_Status_label.setText(_translate("MainWindow", "  System Status : No Alarms"))
        self.Sensors_groupBox.setTitle(_translate("MainWindow", "Sensors:"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Sensor name "))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Latest value "))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Timestamp"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Status "))
        self.Plots_groupBox.setTitle(_translate("MainWindow", "Plots:"))
        self.groupBox.setTitle(_translate("MainWindow", "Temperature Sensor"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Vibration Sensor"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Speed Sensor"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Pressure Sensor"))
        self.groupBox_4.setTitle(_translate("MainWindow", " Optical Counter"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Dashboard"))
        self.Clear_Alarms_Button.setText(_translate("MainWindow", "Clear Alarms"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Alarm Log"))
        self.label_2.setText(_translate("MainWindow", "Live Log Viewer:"))
        self.Restart_Simulation_Button.setText(_translate("MainWindow", "Restart Simulator"))
        self.Force_Refresh_Button.setText(_translate("MainWindow", "Force Refresh"))
        self.Snapshot_of_Values_Button.setText(_translate("MainWindow", "snapshot of values"))
        self.Clear_Alarms_Maintainance_Button.setText(_translate("MainWindow", "Clear Alarms"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Maintenance Console"))
        self.label.setText(_translate("MainWindow", "V1.0.0"))
